package clientcalc;

import ejb.MySessionRemote;
import javax.ejb.EJB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tiago Matias
 */
public class CalcUI extends javax.swing.JFrame {

    @EJB
    private static MySessionRemote mySession;
    private String operation = "";

    /**
     * Creates new form CalcUI
     */
    public CalcUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButCalc1 = new javax.swing.JButton();
        jButCalc2 = new javax.swing.JButton();
        jButCalc3 = new javax.swing.JButton();
        jButCalc4 = new javax.swing.JButton();
        jButCalc5 = new javax.swing.JButton();
        jButCalc6 = new javax.swing.JButton();
        jButCalc7 = new javax.swing.JButton();
        jButCalc8 = new javax.swing.JButton();
        jButCalc9 = new javax.swing.JButton();
        jButCalc0 = new javax.swing.JButton();
        jButSquareRoot = new javax.swing.JButton();
        jButExp1 = new javax.swing.JButton();
        jButCubicRoot = new javax.swing.JButton();
        jButLog = new javax.swing.JButton();
        jButResult = new javax.swing.JButton();
        jButClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setWheelScrollingEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButCalc1.setText("1");
        jButCalc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalc1ActionPerformed(evt);
            }
        });

        jButCalc2.setText("2");
        jButCalc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalc2ActionPerformed(evt);
            }
        });

        jButCalc3.setText("3");
        jButCalc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalc3ActionPerformed(evt);
            }
        });

        jButCalc4.setText("4");
        jButCalc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalc4ActionPerformed(evt);
            }
        });

        jButCalc5.setText("5");
        jButCalc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalc5ActionPerformed(evt);
            }
        });

        jButCalc6.setText("6");
        jButCalc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalc6ActionPerformed(evt);
            }
        });

        jButCalc7.setText("7");
        jButCalc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalc7ActionPerformed(evt);
            }
        });

        jButCalc8.setText("8");
        jButCalc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalc8ActionPerformed(evt);
            }
        });

        jButCalc9.setText("9");
        jButCalc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalc9ActionPerformed(evt);
            }
        });

        jButCalc0.setText("0");
        jButCalc0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalc0ActionPerformed(evt);
            }
        });

        jButSquareRoot.setText("√x");
        jButSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSquareRootActionPerformed(evt);
            }
        });

        jButExp1.setText("x^y");
        jButExp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButExp1ActionPerformed(evt);
            }
        });

        jButCubicRoot.setText("3√x");
        jButCubicRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCubicRootActionPerformed(evt);
            }
        });

        jButLog.setText("logY(x)");
        jButLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButLogActionPerformed(evt);
            }
        });

        jButResult.setText("=");
        jButResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButResultActionPerformed(evt);
            }
        });

        jButClean.setText("C");
        jButClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButCalc4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButCalc5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButCalc6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButCalc7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButCalc0)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButCalc8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButCalc9)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButClean)
                                    .addComponent(jButResult)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButLog, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButCubicRoot)))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButCalc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButCalc2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButCalc3)
                                .addGap(18, 18, 18)
                                .addComponent(jButExp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCalc1)
                    .addComponent(jButCalc2)
                    .addComponent(jButCalc3)
                    .addComponent(jButExp1)
                    .addComponent(jButSquareRoot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCalc4)
                    .addComponent(jButCalc5)
                    .addComponent(jButCalc6)
                    .addComponent(jButCubicRoot)
                    .addComponent(jButLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCalc7)
                    .addComponent(jButCalc8)
                    .addComponent(jButCalc9)
                    .addComponent(jButClean))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCalc0)
                    .addComponent(jButResult))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCalc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalc1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("1");
    }//GEN-LAST:event_jButCalc1ActionPerformed

    private void jButCalc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalc2ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("2");
    }//GEN-LAST:event_jButCalc2ActionPerformed

    private void jButCalc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalc3ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("3");
    }//GEN-LAST:event_jButCalc3ActionPerformed

    private void jButCalc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalc4ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("4");
    }//GEN-LAST:event_jButCalc4ActionPerformed

    private void jButCalc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalc5ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("5");
    }//GEN-LAST:event_jButCalc5ActionPerformed

    private void jButCalc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalc6ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("6");
    }//GEN-LAST:event_jButCalc6ActionPerformed

    private void jButCalc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalc7ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("7");
    }//GEN-LAST:event_jButCalc7ActionPerformed

    private void jButCalc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalc8ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("8");
    }//GEN-LAST:event_jButCalc8ActionPerformed

    private void jButCalc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalc9ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("9");
    }//GEN-LAST:event_jButCalc9ActionPerformed

    private void jButCalc0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalc0ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("0");
    }//GEN-LAST:event_jButCalc0ActionPerformed

    private void jButSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSquareRootActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("√");
        operation += "square";
    }//GEN-LAST:event_jButSquareRootActionPerformed

    private void jButExp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButExp1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("^");
        operation += "exp";
    }//GEN-LAST:event_jButExp1ActionPerformed

    private void jButCubicRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCubicRootActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("3√");
        operation += "cubic";
    }//GEN-LAST:event_jButCubicRootActionPerformed

    private void jButLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButLogActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("log");
        operation += "log";
    }//GEN-LAST:event_jButLogActionPerformed

    private void jButResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButResultActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("\n");
        makeCalculation();
    }//GEN-LAST:event_jButResultActionPerformed

    private void jButCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCleanActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
    }//GEN-LAST:event_jButCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CalcUI().setVisible(true);
        });
    }
    
    
    public void makeCalculation() {
        if(operation.contains("square"))
        {
            operation = "";
            jTextArea1.append("Square\n");
            double result = mySession.squareRoot(2);
            System.err.println("Test result = " + result);
        }
        else if(operation.contains("cubic"))
        {
            operation = "";
            jTextArea1.append("Cubic\n");
            //int result = (int)mySession.cubicSquare(8);
            //jTextArea1.append("Result: " + result);
        }
        else if(operation.contains("log"))
        {
            operation = "";
            int result = (int)mySession.opLog(10,10);
            jTextArea1.append("Result: " + result);
        }
        else if(operation.contains("exp"))
        {
            operation = "";
            int result = (int)mySession.calcExp(2, 2);
            jTextArea1.append("Result: " + result);
        }
        else{
            jTextArea1.append("Operation Not Permitted");
            operation = "";
        }
        
        System.out.println("clientcalc.CalcUI.makeCalculation()");
    }
    
    public Double reader() {
        Double num;
        String str;
        str = jTextArea1.getText();
        num = Double.valueOf(str);

        return num;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButCalc0;
    private javax.swing.JButton jButCalc1;
    private javax.swing.JButton jButCalc2;
    private javax.swing.JButton jButCalc3;
    private javax.swing.JButton jButCalc4;
    private javax.swing.JButton jButCalc5;
    private javax.swing.JButton jButCalc6;
    private javax.swing.JButton jButCalc7;
    private javax.swing.JButton jButCalc8;
    private javax.swing.JButton jButCalc9;
    private javax.swing.JButton jButClean;
    private javax.swing.JButton jButCubicRoot;
    private javax.swing.JButton jButExp1;
    private javax.swing.JButton jButLog;
    private javax.swing.JButton jButResult;
    private javax.swing.JButton jButSquareRoot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
